server.modules = ( "mod_access", "mod_alias", "mod_cgi", "mod_openssl" )

server.document-root = "/www"
server.port = 8443
server.bind = "0.0.0.0"

ssl.engine = "enable"
ssl.pemfile = "/certs/server.pem"

cgi.assign = ( ".sh" => "/bin/bash" )

server.indexfiles = ( "index.html" )
