services:
  rhel:
    container_name: linux-rhel
    hostname: rhel-docker
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
    - "./root:/root"
    - "./home:/home"
